### ISSUE TITLE
actividad_mapa_mental_Daniel_Alejandro

### ISSUE THREAD

**Issue by DanAlejandr** [SistemasTecTlaxiaco/actividad-4-mapa-mental-DanAlejandr#2]
[Conjuntos, funciones y relaciones .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-DanAlejandr/files/12680269/Conjuntos.funciones.y.relaciones.pdf)

**Comment by 23620031** [comment]
MANEJO CONCEPTUAL Y DOMINIO DEL TEMA-> 25/25
RELACIÓN ENTRE LOS CONCEPTOS EN EL MAPA-> 25/25
CALIDAD DE LA PRESENTACIÓN-> 25/25
JERARQUIZACIÓN DE IDEAS-> 25/25

TOTAL=20/20

CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
